package com.wxx.shopping.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wxx.shopping.bean.AddRessInfo;

import com.wxx.shopping.db.AddRessInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig addRessInfoDaoConfig;

    private final AddRessInfoDao addRessInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        addRessInfoDaoConfig = daoConfigMap.get(AddRessInfoDao.class).clone();
        addRessInfoDaoConfig.initIdentityScope(type);

        addRessInfoDao = new AddRessInfoDao(addRessInfoDaoConfig, this);

        registerDao(AddRessInfo.class, addRessInfoDao);
    }
    
    public void clear() {
        addRessInfoDaoConfig.clearIdentityScope();
    }

    public AddRessInfoDao getAddRessInfoDao() {
        return addRessInfoDao;
    }

}
